# pubspec.yaml
name: my_cure_ui
description: MY CURE Login UI with BLoC
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  carousel_slider: ^5.1.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/telangana.png
    - assets/property_tax_banner.png
    - assets/water_bill_banner.png
    - assets/electricity_banner.png
    - assets/trade_license_banner.png
    - assets/echallan_banner.png
    - assets/broadband_banner.png
    - assets/property_tax_photo.png
    - assets/water_bill_photo.png
    - assets/electricity_photo.png
    - assets/trade_license_photo.png
    - assets/echallan_photo.png
    - assets/broadband_photo.png